### ISSUE TITLE
Arbitrary choices for 'General Interest'

### ISSUE THREAD

**Issue by Mustard5** [aaroncox/chainbb-frontend#9]
The choice of General Interest forums seems arbitrary.

Many of them have been inactive for months.  Would it be better to show those that have active posting from the chainbb interface?

I'm obviously a little butthurt that mine is not on there, but put that aside for a minute and consider that people who are encouraging activity should be prioritized for the front page.

**Comment by aaroncox** [comment]
It was arbitrary to be honest, I didn't mean any ill-intent. The forums I choose were actually forums I picked in December (while I was working on this update) and much has changed since then.

The actual goal was for that page to be the default for non-logged in users, and then for users who were logged in, to show which forums they were already subscribed to.

**Comment by Mustard5** [comment]
Okay.  I appreciate you sharing your thoughts and how this particular design decision came about.  I'll close this, as I don't think there is much else that can be said.

Thank you, sir!
